version: 0.2
phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
        - 'echo "Hello, World from NestJS! Built and ready for deployment."'
artifacts:
  files:
    - '**/*'